import type { Config } from 'tailwindcss';
import { COLORS, SURFACES } from '@priorbyte/shared/brand';

/**
 * Cognitive Blueprint theme. Colors come from /shared so the extension and
 * any future surface stay on the same palette.
 */
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: COLORS.background,
        surface: SURFACES.surface,
        'surface-raised': SURFACES.surfaceRaised,
        line: SURFACES.line,
        muted: SURFACES.muted,
        cyan: { DEFAULT: COLORS.cyan },
        teal: { DEFAULT: COLORS.teal },
        amber: { DEFAULT: COLORS.amber },
        silver: { DEFAULT: COLORS.silver },
      },
      fontFamily: {
        display: ['var(--font-sora)', 'system-ui', 'sans-serif'],
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        glow: `0 0 24px -6px ${COLORS.cyan}66`,
        'glow-teal': `0 0 24px -6px ${COLORS.teal}66`,
      },
      backgroundImage: {
        // Thin cyan geometric grid used behind hero and dashboard sections.
        blueprint:
          'linear-gradient(to right, rgba(0,229,255,0.05) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,229,255,0.05) 1px, transparent 1px)',
      },
      // Named `blueprint-grid` so it does not collide with the `bg-blueprint`
      // utility generated by backgroundImage above.
      backgroundSize: {
        'blueprint-grid': '48px 48px',
      },
      keyframes: {
        pulseEye: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.45' },
        },
      },
      animation: {
        'pulse-eye': 'pulseEye 2.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
