import type { Config } from 'tailwindcss';
import { COLORS } from '@priorbyte/shared/brand';

/**
 * Cognitive Blueprint theme. Most tokens resolve through CSS variables
 * (defined in globals.css) rather than static hex, so per-user theme and
 * accent-color preferences repaint the whole app without per-component
 * changes. `teal` and `amber` stay static — they carry fixed semantic
 * meaning (success / warning) independent of the user's chosen accent.
 */
const withAlpha = (cssVar: string) => `rgb(var(${cssVar}) / <alpha-value>)`;

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: withAlpha('--pb-bg'),
        surface: withAlpha('--pb-surface'),
        'surface-raised': withAlpha('--pb-surface-raised'),
        line: withAlpha('--pb-line'),
        muted: withAlpha('--pb-muted'),
        silver: { DEFAULT: withAlpha('--pb-silver') },
        white: withAlpha('--pb-heading'),
        cyan: { DEFAULT: withAlpha('--pb-accent') },
        teal: { DEFAULT: COLORS.teal },
        amber: { DEFAULT: COLORS.amber },
      },
      fontFamily: {
        display: ['var(--font-anton)', 'system-ui', 'sans-serif'],
        // Body text runs in JetBrains Mono system-wide — the "diagnostic
        // terminal" read the Cyber-Academic system calls for, not a
        // decorative choice confined to code blocks.
        sans: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
        mono: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
        label: ['var(--font-space-grotesk)', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        // Static, not CSS-var-driven: an accent-reactive glow is a nice-to-have,
        // not worth the added complexity of a var-based box-shadow color.
        glow: `0 0 24px -6px ${COLORS.cyan}66`,
        'glow-teal': `0 0 24px -6px ${COLORS.teal}66`,
      },
      backgroundImage: {
        // Thin cyan geometric grid used behind hero and dashboard sections.
        blueprint:
          'linear-gradient(to right, rgba(0,229,255,0.05) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,229,255,0.05) 1px, transparent 1px)',
      },
      // Named `blueprint-grid` so it does not collide with the `bg-blueprint`
      // utility generated by backgroundImage above.
      backgroundSize: {
        'blueprint-grid': '48px 48px',
      },
      keyframes: {
        pulseEye: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.45' },
        },
      },
      animation: {
        'pulse-eye': 'pulseEye 2.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
